/**
 * Plantilla de Importación de Justificaciones ICFES (Versión Compacta)
 */

var JUSTIFICACIONES_IMPORT = [
  {
    idPregunta: 81,
    nombrePregunta: "",
    descripcionExtendida: "Esta pregunta evalua vocabulario de salud y emociones en ingles (nivel A1). El enunciado \"Some people do this when they feel really sad or sick\" pide identificar una accion que las personas realizan cuando estan tristes o enfermas. De todas las opciones, solo C. cry (llorar) es un verbo/accion que se asocia tanto con la tristeza como con el malestar fisico. Las demas opciones son sustantivos: lugares (hospital), personas (doctor), objetos (medicine) o sintomas (cold, cough, stomach-ache).",
    mediaInteractiva: "<iframe srcdoc=\"<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;margin:0;padding:10px;background:linear-gradient(135deg,#e0f2fe,#dbeafe);min-height:100vh;display:flex;align-items:center;justify-content:center}.card{background:#fff;border-radius:12px;padding:12px;width:100%;max-width:320px;box-shadow:0 4px 12px rgba(0,0,0,0.1)}.tag{font-size:10px;text-transform:uppercase;color:#3b82f6;font-weight:700;margin-bottom:6px}.q{font-size:13px;color:#1e293b;margin-bottom:8px}.opts{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-bottom:10px}.btn{padding:12px 10px;font-size:12px;border:2px solid #e2e8f0;background:#fff;cursor:pointer;border-radius:8px}.btn:hover{background:#f1f5f9}.result{text-align:center;font-size:11px;min-height:24px;padding:8px;border-radius:6px;margin-top:8px;background:#f1f5f9;color:#64748b}.result.correct{background:#dcfce7;color:#166534}.result.wrong{background:#fee2e2;color:#991b1b}</style></head><body><div class='card'><div class='tag'>Accion o Cosa?</div><div class='q'>Elige la palabra que es una ACCION (verbo)</div><div class='opts' id='opts'></div><div class='result' id='result'>Click en una opcion</div></div><script>var opts=[{w:'Cold',correct:false},{w:'Doctor',correct:false},{w:'Cry',correct:true},{w:'Medicine',correct:false}];var result=document.getElementById('result');opts.forEach(function(o,i){var btn=document.createElement('button');btn.className='btn';btn.textContent=o.w;btn.onclick=function(){if(o.correct){result.className='result correct';result.textContent='Correcto! ' + o.w + ' es una ACCION (se hace)';}else{result.className='result wrong';result.textContent='No, ' + o.w + ' es una COSA. Intenta otra!';}};document.getElementById('opts').appendChild(btn);});</script></body></html>\" style=\"width:100%;height:280px;border:none;\"></iframe>",
    glosarioItems: "cold:resfriado/cold:toser/cry:llorar/doctor:medico/hospital:hospital/medicine:medicina/stomach-ache:dolor de estomago",
    datoCurioso: "Las lagrimas emocionales contienen leucina-encefalina, un analgesico natural producido por el cerebro.",
    errorComunFeedback: "El error mas frecuente es elegir B. cough (toser), ya que toser se asocia con enfermedad pero no con Tristeza."
  },
  {
    idPregunta: 82,
    nombrePregunta: "",
    descripcionExtendida: "Esta pregunta pertenece al mismo ejercicio de vocabulario de salud (nivel A1). El enunciado \"You can take this when you have a terrible headache\" usa el verbo take como pista: busca algo que se ingiere o consume. Solo medicine se puede tomar.",
    mediaInteractiva: "<iframe srcdoc=\"<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;margin:0;padding:10px;background:linear-gradient(135deg,#dcfce7,#bbf7d0);min-height:100vh;display:flex;align-items:center;justify-content:center}.card{background:#fff;border-radius:12px;padding:12px;width:100%;max-width:320px;box-shadow:0 4px 12px rgba(0,0,0,0.1)}.tag{font-size:10px;text-transform:uppercase;color:#16a34a;font-weight:700;margin-bottom:4px}.q{font-size:12px;color:#1e293b;margin-bottom:6px}.hint{font-size:9px;background:#fef3c7;color:#92400e;padding:4px 8px;border-radius:4px;margin-bottom:8px;display:inline-block}.opts{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-bottom:10px}.btn{padding:12px 10px;font-size:12px;border:2px solid #d1fae5;background:#fff;cursor:pointer;border-radius:8px}.btn:hover{background:#ecfdf5}.result{text-align:center;font-size:11px;min-height:24px;padding:8px;border-radius:6px;margin-top:8px;background:#f1f5f9;color:#64748b}.result.correct{background:#dcfce7;color:#166534}.result.wrong{background:#fee2e2;color:#991b1b}</style></head><body><div class='card'><div class='tag'>Take = Consumir</div><div class='q'>Que se puede TOMAR (consumir)?</div><div class='hint'>take = consumir / beber</div><div class='opts' id='opts'></div><div class='result' id='result'>Click en una opcion</div></div><script>var opts=[{w:'Doctor',correct:false},{w:'Cold',correct:false},{w:'Medicine',correct:true},{w:'Hospital',correct:false}];var result=document.getElementById('result');opts.forEach(function(o,i){var btn=document.createElement('button');btn.className='btn';btn.textContent=o.w;btn.onclick=function(){if(o.correct){result.className='result correct';result.textContent='Correcto! ' + o.w + ' se puede TOMAR';}else{result.className='result wrong';result.textContent='No, ' + o.w + ' no se puede tomar. Intenta otra!';}};document.getElementById('opts').appendChild(btn);});</script></body></html>\" style=\"width:100%;height:280px;border:none;\"></iframe>",
    glosarioItems: "cold:resfriado/cough:tos/cry:llorar/doctor:medico/hospital:hospital/medicine:medicina/headache:dolor de cabeza",
    datoCurioso: "El dolor de cabeza tensional es el tipo mas comun en el mundo.",
    errorComunFeedback: "Ninguna otra opcion es algo que se pueda tomar."
  }
];